language: ruby
cache: bundler
rvm:
- ruby-2.2.2
env:
  - DB=sqlite
services:
  - elasticsearch
  - postgresql 
before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.2.4.deb && sudo service elasticsearch restart
before_script:
  - sleep 10
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake cucumber
  - bundle exec rake spec/

addons:
  code_climate:
    repo_token: c97988e6ff0969f56fc41dd6ca3c42fe42b0a0ee8ea8a4a96066f3e1c042256b
    
# language: ruby
# rvm:
#   - '2.2.2'
# addons:
#   code_climate:
#   repo_token: c97988e6ff0969f56fc41dd6ca3c42fe42b0a0ee8ea8a4a96066f3e1c042256b

after_success:
  - coveralls